apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30" # Deploy ingress last to expose services only after workloads are running.

spec:
  project: default

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.0

    helm:
      releaseName: ingress-nginx
      # DaemonSet - Run one ingress controller Pod on every Kubernetes node
      # hostPort:true - Expose ports 80 and 443 directly on every node without requiring a LoadBalancer or NodePort Service.
      # ClusterIP -  Internal Service used for in-cluster communication only (default one)
      # admissionWebHooks:enabled -  Enable validation webhooks for Ingress resources.
      # Patch:enabled - Automatically configure TLS certificates required by the admission webhook.

      values: |
        controller:
          kind: DaemonSet

          hostPort:
            enabled: true

          service:
            type: ClusterIP

        admissionWebhooks:
          enabled: true

          patch:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
