apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Deploy observability first so platform components are monitored from the start.

spec:
  project: default

  source:
    repoURL: https://github.com/Skowronf/enterprise-platform
    targetRevision: main
    path: charts/petclinic-platform/charts/observability

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
