postgres:
  enabled: false

aws:
  enabled: true

database:
  externalSecret:
    enabled: true

    secretStore:
      name: aws-secretsmanager
      kind: ClusterSecretStore

    remoteSecret:
      key: petclinic/database
