replicaCount: 2

image:
  repository: ghcr.io/skowronf/petclinic
  tag: 22e6589b435ea5d8e9dc9409691c2b16a5dd0e8e

imagePullSecrets: []

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 1000m
    memory: 1Gi

# AWS uses Amazon RDS instead of PostgreSQL running inside Kubernetes.
postgres:
  enabled: false

aws:
  enabled: true

certificate:
  enabled: false

database:
  externalSecret:
    enabled: true

    secretStore:
      name: aws-secretsmanager
      kind: ClusterSecretStore

    remoteSecret:
      key: petclinic/database
