replicaCount: 2
image:
  repository: ghcr.io/skowronf/petclinic
  tag: c6e8c73a8a7ff5324209aa1e115d5bcda1fd5c6e
imagePullSecrets:
  - name: ghcr-secret
resources:
  requests: # Minimum resources Kubernetes reserves for scheduling this container used by scheduler
    cpu: 250m
    memory: 512Mi
  limits: # Maximum resources the container can use before being throttled (CPU) or OOMKilled (memory)
    cpu: 1000m
    memory: 1Gi
