replicaCount: 2
image:
  repository: ghcr.io/skowronf/petclinic
  tag: 312569c0f013bccfae795a600377371fff8f9856
imagePullSecrets:
  - name: ghcr-secret
resources:
  requests: # Minimum resources Kubernetes reserves for scheduling this container used by scheduler
    cpu: 250m
    memory: 512Mi
  limits: # Maximum resources the container can use before being throttled (CPU) or OOMKilled (memory)
    cpu: 1000m
    memory: 1Gi
