apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          env:
            - name: PGPASSWORD
              value: petclinic
          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h postgres \
                -p 5432 \
                -U petclinic \
                -d petclinic
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
      containers:
        - name: petclinic
          image: petclinic:ci
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
