apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: petclinic
            - name: POSTGRES_USER
              value: petclinic
            - name: POSTGRES_PASSWORD
              value: petclinic


          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U petclinic
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U petclinic
            initialDelaySeconds: 20
            periodSeconds: 10
