apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: petclinic
  PGPASSWORD: petclinic # Should be hashed by me before giving it here
