apiVersion: apps/v1
kind: Deployment # Makes a Pod with a label, then Service can find this pod using selector with same label
metadata:
  name: petclinic
  namespace: petclinic # Will be made in this namespace
spec:
  replicas: 1 # Kubernetes will keep up one pod running, if it dies new one will be created
  selector:
    matchLabels: # Deployment finds Pod with this label, must be the same as label in template
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic # Each new Pod will get this label, used by Deployment and Service
    spec:
      initContainers: # Run before main container, main container won't start until this one ends successfully
        - name: wait-for-postgres
          image: postgres:16
          envFrom:
            - secretRef: # use Secret to pass credentials
                name: petclinic-secret
          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h postgres \
                -p 5432 \
                -U petclinic \
                -d petclinic
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
      containers:
        - name: petclinic
          image: petclinic:ci
          imagePullPolicy: Never # Don't pull image from registry ( I have it locally )
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: # Use configMap for configuration storage
                name: petclinic-config
          readinessProbe: # Make sure application is ready for traffic, Service won't use pod until it is
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
