apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.21.1

    helm:
      values: |
        provider:
          name: aws

        sources:
          - ingress

        policy: sync

        registry: txt
        txtOwnerId: petclinic-eks

        domainFilters:
          - petclinic.website

        serviceAccount:
          create: true
          name: external-dns

        extraArgs:
          ingress-class: alb
          aws-zone-type: public

        triggerLoopOnEvent: true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
