apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-secrets-store
  namespace: argocd

  annotations:
    # Deploy after External Secrets Operator is available.
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/Skowronf/kubernetes
    targetRevision: HEAD
    path: aws-platform/cluster-secret-store.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
