apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx
  namespace: petclinic

spec:
  podSelector:
    matchLabels:
      app: petclinic

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
# Pods in the 'petclinic' namespace with the label 'app: petclinic'
# can receive TCP traffic on port 8080 only from Pods in the
# 'ingress-nginx' namespace.