apiVersion: networking.k8s.io/v1
kind: Ingress
# Ingress is a way to expose HTTP and HTTPS routes from 
# OUTSIDE the cluster to services WITHIN the cluster. 

metadata:
  name: petclinic

  labels:
    app: petclinic

spec:

  ingressClassName: nginx

  rules:
    - host: petclinic.local

      http:
        paths:
          - path: /

            pathType: Prefix

            backend: # Ingress -> Service -> Pod
              service:
                name: petclinic-stable

                port:
                  number: 8080
