apiVersion: networking.k8s.io/v1
kind: Ingress
# Ingress is a way to expose HTTP and HTTPS routes from 
# OUTSIDE the cluster to services WITHIN the cluster. 

metadata:
  name: petclinic
  labels:
    app: petclinic
  namespace: petclinic
  annotations:
    {{- if .Values.certificate.enabled }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}

spec:
  ingressClassName: nginx
  {{- if .Values.certificate.enabled }}
  tls:
    - hosts:
        - petclinic.local
      secretName: petclinic-tls
  {{- end }}

  rules:
  - host: petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-stable
            port:
              number: 8080
