apiVersion: networking.k8s.io/v1
kind: NetworkPolicy 
metadata:
  name: petclinic-allow-to-postgres
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: petclinic
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
# Allow PetClinic Pods to connect to PostgreSQL Pods
# on TCP port 5432 for database communication.