{{- if .Values.database.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-database
  namespace: petclinic
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.database.externalSecret.secretStore.name }}
    kind: {{ .Values.database.externalSecret.secretStore.kind }}

  target:
    name: petclinic-database
    creationPolicy: Owner
    
  # Keys to fetch from the remote secret and create in the target secret.
  dataFrom:
    - extract:
        key: {{ .Values.database.externalSecret.remoteSecret.key }}
{{- end }}
