apiVersion: argoproj.io/v1alpha1
kind: Rollout # Argo Rollouts replacement for Deployment, manages ReplicaSets and progressive delivery
metadata:
  name: petclinic
  namespace: petclinic # Will be made in this namespace

spec:
  replicas: {{ .Values.replicaCount }} # Rollout will keep that many pods running, if they die, they will be created again

  selector:
    matchLabels: # Rollout finds Pod with this label, must be the same as label in template
      app: petclinic

  strategy:
    canary:
      stableService: petclinic-stable
      canaryService: petclinic-canary
      trafficRouting:
        nginx:
          stableIngress: petclinic # name of existing Ingress, managed by Argo Rollouts
          # Existing stable Ingress managed by Argo Rollouts.
          # Rollouts will automatically create/update a Canary Ingress
          # and adjust traffic weights during deployment.

      steps:
        - setWeight: 20

        - analysis:
            templates:
              - templateName: petclinic-success-rate

        - pause:
            duration: 60s

        - setWeight: 50

        - analysis:
            templates:
              - templateName: petclinic-success-rate

        - pause:
            duration: 60s

        - setWeight: 100

  template:
    metadata:
      labels:
        app: petclinic

    spec:

      # Pod-level security configuration.
      # Applies to all containers running inside this Pod.
      securityContext:

        # Prevent containers from running with root privileges.
        # Kubernetes will reject the Pod if the container attempts to run as UID 0.
        runAsNonRoot: true

        # Force application processes to run using the dedicated application user.
        runAsUser: 1000

        # Force application processes to run using the dedicated application group.
        runAsGroup: 3000

        # Ensure mounted volumes are accessible by the application group.
        fsGroup: 2000


      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}


      volumes:

        # Spring Boot uses /tmp for temporary files.
        # Since the container filesystem is read-only,
        # provide a writable temporary filesystem.
        - name: tmp
          emptyDir: {}


      initContainers:

        - name: wait-for-postgres

          image: postgres:16

          envFrom:
            - secretRef:
                name: petclinic-secret

          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h postgres \
                -p 5432 \
                -U petclinic \
                -d petclinic
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

      containers:

        - name: petclinic


          securityContext:

            # Prevent processes inside the container from gaining
            # additional privileges.
            allowPrivilegeEscalation: false


            # Remove all Linux capabilities that are not required.
            # The application runs with the minimum required permissions.
            capabilities:
              drop:
                - ALL


            # Make the container root filesystem read-only.
            # Prevents modification of binaries and system files at runtime.
            readOnlyRootFilesystem: true


          resources:
            {{- toYaml .Values.resources | nindent 12 }}


          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"


          imagePullPolicy: Always


          ports:

            - containerPort: 8080


          volumeMounts:

            # Writable temporary directory required by JVM/Spring Boot.
            - name: tmp
              mountPath: /tmp


          envFrom:

            - configMapRef:
                name: petclinic-config


          readinessProbe:

            httpGet:
              path: /
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 30