apiVersion: argoproj.io/v1alpha1
kind: Rollout # Argo Rollouts replacement for Deployment, manages ReplicaSets and progressive delivery
metadata:
  name: petclinic
  namespace: petclinic # Will be made in this namespace

spec:
  replicas: {{ .Values.replicaCount }} # Rollout will keep that many pods running, if they die, they will be created again

  selector:
    matchLabels: # Rollout finds Pod with this label, must be the same as label in template
      app: petclinic

  strategy:
    canary:
      stableService: petclinic-stable
      canaryService: petclinic-canary
      trafficRouting:
        nginx:
          stableIngress: petclinic # name of existing Ingress, managed by Argo Rollouts
          # Existing stable Ingress managed by Argo Rollouts.
          # Rollouts will automatically create/update a Canary Ingress
          # and adjust traffic weights during deployment.

      steps:
        - setWeight: 20 # Send 20% traffic to the new version.

        - pause:
            duration: 60s

        # Increase traffic to 50%.
        - setWeight: 50

        # Pause again before full promotion.
        - pause:
            duration: 60s

        # Send all traffic to the new version.
        - setWeight: 100

  template:
    metadata:
      labels:
        app: petclinic # Each new Pod will get this label, used by Rollout and Service

    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      initContainers: # Run before main container, main container won't start until this one ends successfully
        - name: wait-for-postgres

          image: postgres:16

          envFrom:
            - secretRef: # use Secret to pass credentials
                name: petclinic-secret

          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h postgres \
                -p 5432 \
                -U petclinic \
                -d petclinic
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

      containers:

        - name: petclinic

          resources: {{- toYaml .Values.resources | nindent 12 }} # from values.yaml, whole resources block to yaml, indented 12 spaces

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: Always # Pull image every time a Pod starts

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef: # Use configMap for configuration storage
                name: petclinic-config

          readinessProbe: # Make sure application is ready for traffic, Service won't use pod until it is
            httpGet:
              path: /
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 30