{{- if not .Values.postgres.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: petclinic-allow-rds
  namespace: petclinic
spec:
  endpointSelector:
    matchLabels:
      app: petclinic
  egress:
    # For now - Allow egress to WHOLE private subnet to reach RDS instance. 
    # In future, we can restrict it to RDS instance only.
    # Coudnt find a way to do it with CiliumNetworkPolicy
    # Cannot use external secret to get pass value of RDS instance endpoint and use it in the cilium policy.
    - toCIDR:
        - 10.0.10.0/24
        - 10.0.11.0/24
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
{{- end }}