apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: petclinic

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  volumeName: postgres-backups