apiVersion: apps/v1
kind: StatefulSet # Creates Pods with stable identity and stable storage, StatefulSet creates one PVC per Pod automatically
metadata:
  name: postgres
  namespace: petclinic

spec:
  replicas: 1

  serviceName: postgres # Name of Headless Service used for stable DNS

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: petclinic

            - name: POSTGRES_USER
              value: petclinic

            - name: POSTGRES_PASSWORD
              value: petclinic


          readinessProbe: # Service sends traffic only when PostgreSQL is ready
            exec:
              command:
                - sh
                - -c
                - pg_isready -U petclinic

            initialDelaySeconds: 5
            periodSeconds: 30


          livenessProbe: # Kubernetes restarts container if PostgreSQL is unhealthy
            exec:
              command:
                - sh
                - -c
                - pg_isready -U petclinic

            initialDelaySeconds: 20
            periodSeconds: 30


          volumeMounts: # Must match volumeClaimTemplates name
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:

    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi