apiVersion: networking.k8s.io/v1
kind: NetworkPolicy 
metadata:
  name: postgres-allow-ingress-from-petclinic
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: petclinic
    - podSelector:
        matchLabels:
          app: postgres-backup
    ports:
    - protocol: TCP
      port: 5432
# Allow PostgreSQL Pods to receive TCP traffic on port 5432
# from PetClinic Pods for database connections.